language: rust
dist: trusty
matrix:
  include:
  - os: osx
    rust: stable
    env: TARGET=x86_64-apple-darwin
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
before_script:
- rustc -V
- cargo -V
- git --version
- echo $TRAVIS_BRANCH
- git checkout $TRAVIS_BRANCH
- git rev-parse HEAD
script:
- cargo build --target $TARGET
- cargo test --verbose
notifications:
  email:
    on_success: never
    on_failure: change
before_deploy:
- cargo build --target $TARGET --release
- mkdir "chema-${TRAVIS_TAG}-${TARGET}"
- cp target/$TARGET/release/chema LICENSE README.md "chema-${TRAVIS_TAG}-${TARGET}"
- zip "chema-${TRAVIS_TAG}-${TARGET}.zip" -r "chema-${TRAVIS_TAG}-${TARGET}"
- tar czf "chema-${TRAVIS_TAG}-${TARGET}.tar.gz" "chema-${TRAVIS_TAG}-${TARGET}"
deploy:
  provider: releases
  api_key:
    secure: spah/E0qzAYBgeqpWqPrkytcg/T72A9QxX9qEbepAsYRrsTfDZwsGB64YXRu7XcoAoDRZwbYxD+fCNHIgIUjXIIE9sli3RehYVa2LOCas0RAhNHriXaouOxAWaZYSICMgdAX4/T89bA2u/6+M1jSO+7U4gSdjq6L4tpNQc4iFTRLv9CRD3pwNQ5USbJSRR4Pox3y87eDmssLUS59WpjTOkiVI4pIRF5erH8qjb189dklxzMPlGIYKsR3T4ocp7rESEh1z6cgXDfTm6NqFOLCaNZ1AHkh1j0AULeibsi7vBdQU0fECgheQ+b6qs4dWotwJzc1EuAUtSaR66dVLYKUEMUtdRj9+DkqM6tIUgTAzzsqrbWYV39Wwegf9U7FRlJNEWFeyOGQLGj58DiebPVMWElgeYFVNYRobwlI/oEblaozdPmNdf+QD4QZxyA7vnlz2Vl0nH2gJnkII1QQwZiXoB1P2lC1ThI4Fjt2PR5HTWnCW3gR8pfOf8txwWHth8LCusug2PIibUtccohcp9QvkCFJ1AeLIOwRRfDL3rmlQ97/oOvJ9/rWzOprBfBWq2+aImuRv8EdFRTK4okAVwa8nHm/44I9dVt/7CUtbb/7e+1B21mNz8dOfiwuGaRfOSTexLBoxT060SOJEfRvK4Mw6pJKyCdwKOnJRG0ys79HeGA=
  skip-cleanup: true
  file:
    - chema-${TRAVIS_TAG}-${TARGET}.zip
    - chema-${TRAVIS_TAG}-${TARGET}.tar.gz
  on:
    branch: master
    repo: KeenS/chema
    tags: true
